
width = 204.8
height = 204.8

function init(self)
	msg.post(".", "acquire_input_focus")
	screenX , screenY = window.get_size()
end
function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		if action.x <= go.get_position().x + width/2 and action.x >= go.get_position().x - width/2 then
			if action.y <= go.get_position().y + height/2 and action.y >= go.get_position().y - height/2 then
				msg.post("/ui#hud", "AddClicks",{1})
			end
		end
	end
end