
function init(self)
	msg.post(".", "acquire_input_focus")
end
function on_input(self, action_id, action)
	if action_id == hash("up") and action.pressed then
		local pos = vmath.vector3()
		local pos = go.get_position()
		pos.y = pos.y + 51.2
		go.set_position(pos)
	end
	if action_id == hash("down") and action.pressed then
		local pos = go.get_position()
		pos.y = pos.y - 51.2
		go.set_position(pos)
	end
end

